
let productDt = [
    {
       id : '1',
       imageUrl : '/image/Dark Futuristic Wave Lines Desktop Background (2) - Copy.png',
       CurrentPrice :'7500DA',
       oldPrice :'4500DA',
       reduction :'-3% ',
       newProduct : 'offrebienvenue ',
       productSold : '+10000',
       review : '4.4',
       productName : 'jet',
       freeDelevery : 'Livraison gratuite',
    },
    {
        id : '2',
        imageUrl : '/image/Dark Futuristic Wave Lines Desktop Background (2) - Copy.png',
        CurrentPrice :'1500DA',
        oldPrice :'8500DA',
        reduction :'-3% ',
        newProduct : 'offrebienvenue ',
        productSold : '+10000 ',
        review : '4.4',
        productName : 'plan',
        freeDelevery : 'Livraison gratuite',
     },
     {
        id : '3',
        imageUrl : '/image/Dark Futuristic Wave Lines Desktop Background (2) - Copy.png',
        CurrentPrice :'0500DA',
        oldPrice :'4500DA',
        reduction :'-3% ',
        newProduct : 'offrebienvenue ',
        productSold : '+6000 ',
        review : '4.4',
        productName : 'bike',
        freeDelevery : 'Livraison gratuite',
     },
     {
        id : '4',
        imageUrl : '/image/Dark Futuristic Wave Lines Desktop Background (2) - Copy.png',
        CurrentPrice :'5000DA',
        oldPrice :'2000DA',
        reduction :'-3% ',
        newProduct : 'offrebienvenue ',
        productSold : '+5000 ',
        review : '4.4',
        productName : 'car',
        freeDelevery : 'Livraison gratuite',
     },
     {
        id : '5',
        imageUrl : '/image/Dark Futuristic Wave Lines Desktop Background (2) - Copy.png',
        CurrentPrice :'58000DA',
        oldPrice :'2000DA',
        reduction :'-3% ',
        newProduct : 'offrebienvenue ',
        productSold : '+5000 ',
        review : '4.4',
        productName : 'car',
        freeDelevery : 'Livraison gratuite',
     },
     
];
localStorage.setItem('productdetails', JSON.stringify(productDt));